language: python
python:
  - "2.7"

before_install: "pip install -r requirements.txt"
script:
  #- python tests.py
  - cd Version_A/tema_1
  - "python -m coverage run test_caso1.py"

after_script: "coveralls"